package com.app;

import static com.app.FrmViewTransaction.transactionid;
import static com.app.SQLite.conn;
import static com.app.SQLite.stmt;
import static com.app.SQLite.url;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class FrmViewProduct extends javax.swing.JFrame {

    public FrmViewProduct() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.viewTable();
        comboboxItem();
        
        SimpleDateFormat dateFormat1 = new SimpleDateFormat("MMM dd, yyyy");
        String currentDate = dateFormat1.format(new Date());
        lDate.setText(currentDate);
    }
    public void viewTable(){
            if (SQLite.openDB()) {
                String[][] data = SQLite.read1("tblSales_Details", " SalesID = " + transactionid);
                String[] column = {"SalesDetailsID", "Sales_Date", "SalesID", "ProductID"};
                javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(data, column);
                this.tbSalesDetails.setModel(model);
                SQLite.closeDB();
            }
             this.refreshTable();
        }
    
     public void refreshTable(){
        if(SQLite.openDB()){

            String[] columns = {"SalesDetailsID", "Sales_Date", "SalesID", "ProductID"};
            String[][] records = SQLite.read2("tblSales_Details",columns);
            javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(records, columns){
                public boolean isEditable(){
                    return false;
                }
            };
            
            SQLite.closeDB();
        } 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSalesDetails = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID_edit = new javax.swing.JTextField();
        txtID_delete = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        cbProduct = new javax.swing.JComboBox<>();
        txtProductname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSupname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lDate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbSalesDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbSalesDetails.setEnabled(false);
        jScrollPane1.setViewportView(tbSalesDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 11, 580, 286));

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 105, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Details ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 105, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sales Details ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 100, -1));

        txtID_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtID_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 110, -1));

        txtID_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtID_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 490, 105, -1));

        btnDelete.setBackground(new java.awt.Color(255, 51, 0));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, 105, 36));

        btnEdit.setBackground(new java.awt.Color(0, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel1.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 110, 36));

        btnBack.setBackground(new java.awt.Color(255, 0, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 620, 103, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Product Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Sales Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        txtID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtID.setEnabled(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 140, -1));

        cbProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductActionPerformed(evt);
            }
        });
        jPanel1.add(cbProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 141, -1));

        txtProductname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtProductname.setEnabled(false);
        jPanel1.add(txtProductname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 141, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Supplier Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        btnSubmit.setBackground(new java.awt.Color(0, 153, 255));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSubmit.setText("Buy a Product");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 290, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("ProductID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        txtSupname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSupname.setEnabled(false);
        jPanel1.add(txtSupname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 580, 141, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Sales Details ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        lDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lDate.setEnabled(false);
        jPanel1.add(lDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 141, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        FrmViewTransaction m = new FrmViewTransaction();
        m.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
           if(SQLite.openDB()){
               String[][] r = SQLite.read1("tblSales_Details", "SalesDetailsID =" + this.txtID_delete.getText());
               if(r.length > 0){
                   
                if(SQLite.delete1("tblSales_Details", "Salesdetailsid = " + Integer.parseInt(this.txtID_delete.getText()))){
                 javax.swing.JOptionPane.showMessageDialog(null, "Deleted!");
                 
                 }
                 else{
                     javax.swing.JOptionPane.showMessageDialog(null, "Delete Error!");
                 }
               }
               else{
                   javax.swing.JOptionPane.showMessageDialog(null, "Cannot find ID");
               }
            }
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cannot find ID");
        }
         SQLite.closeDB();
        this.viewTable();
        this.txtID_delete.setText("");
        this.txtID_edit.setText("");
    }//GEN-LAST:event_btnDeleteActionPerformed
public static int carID;
    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try{
            if(SQLite.openDB()){
                String[][] r = SQLite.read1("tblSales_Details", "SalesDetailsID =" + this.txtID_edit.getText());

                if(r.length > 0){
                    carID = Integer.parseInt(this.txtID_edit.getText());

                    FrmUpdateTransaction m = new FrmUpdateTransaction();
                    m.setVisible(true);
                }
                else{
                    javax.swing.JOptionPane.showMessageDialog(null, "Cannot find ID");
                }
            }
        }catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Cannot find ID");
        }
        SQLite.closeDB();
        this.viewTable();
        this.txtID_delete.setText("");
        this.txtID_edit.setText("");
    }//GEN-LAST:event_btnEditActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.viewTable();
        this.txtID_delete.setText("");
        this.txtID_edit.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void comboboxItem(){
        try{
            SQLite.conn = getConnection(SQLite.url);
            SQLite.stmt = SQLite.conn.createStatement();
            
            String query = "select * from tblSales_Details";
            ResultSet rs = SQLite.stmt.executeQuery(query);
            
            while(rs.next()){
                int id= Integer.parseInt(rs.getString("SalesDetailsID"));
                
                int genID = id+1;
                this.txtID.setText(String.valueOf(genID));
            }
            
            String q = "select * from tblProduct";
            ResultSet rss = SQLite.stmt.executeQuery(q);
            
            while(rss.next()){
                String name= rss.getString("ProductID");
                this.cbProduct.addItem(name);
            }
            
            String qq = "select * from tblProduct where ProductID=" + this.cbProduct.getSelectedItem();
            ResultSet rsss = SQLite.stmt.executeQuery(qq);
            
            while(rss.next()){
                this.txtProductname.setText(rss.getString("Product_Name"));
            }
            
            conn.close();
       }
       catch(Exception e){
           System.out.println("error: " + e.getMessage());
       }
    }
    
    public boolean validateProduct(){
            boolean result = false;
            int product_id = 0;
            int sales_id = 0;

            try{
                conn = getConnection(url);
                stmt = conn.createStatement();

                String query = "select * from tblSales_Details where salesid=" + transactionid ;

                ResultSet rs = stmt.executeQuery(query);

                while(rs.next()){
                    product_id = Integer.parseInt(rs.getString("ProductID"));
                    if(product_id == Integer.parseInt(cbProduct.getSelectedItem().toString())){
                        System.out.println("Found!");
                        result = true;
                    }
                }
            } catch(Exception e){
                System.out.println("Not Found!");
            }

            return result;
        }

    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        if(validateProduct()){
            javax.swing.JOptionPane.showMessageDialog(null, "Try Another Product ID");
        }
            if(SQLite.openDB()){
                try{
                    String dateStart = lDate.getText();

                    int Cno = Integer.parseInt((String) this.cbProduct.getSelectedItem());

                    String values = "'" +  dateStart + "'," + transactionid + "," + Cno;
                    String set = "Sales_Date, SalesID, ProductID";

                    SQLite.create("tblSales_Details", set, values);

                    String name = this.txtProductname.getText();
                    int cartype = 0;

                    javax.swing.JOptionPane.showMessageDialog(null, "New Transaction Created!");
                    this.viewTable();
                    this.txtID_delete.setText("");
                    this.txtID_edit.setText("");
                }
                catch(Exception e){
                    javax.swing.JOptionPane.showMessageDialog(null, "Create Error: " + e.getMessage());
                }
            }
        SQLite.closeDB();
        this.viewTable();
        this.txtID_delete.setText("");
        this.txtID_edit.setText("");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void cbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductActionPerformed
        try{
            SQLite.conn = getConnection(SQLite.url);
            SQLite.stmt = SQLite.conn.createStatement();
            String query = "select * from tblProduct where ProductID=" + this.cbProduct.getSelectedItem();
            String query2 = "select * from tblSupplier where SupplierID=" + this.cbProduct.getSelectedItem();

            ResultSet rs = SQLite.stmt.executeQuery(query);
            while(rs.next()){
                String name= rs.getString("ProductID");
                this.txtProductname.setText(rs.getString("Product_Name"));
            }

            ResultSet rss = SQLite.stmt.executeQuery(query2);
            while(rss.next()){
                String name= rss.getString("SupplierID");
                this.txtSupname.setText(rs.getString("Supplier_Name"));
            }
        }
        catch(Exception e){
            System.out.println("error: " + e.getMessage());
        }
    }//GEN-LAST:event_cbProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmViewProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmViewProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lDate;
    private javax.swing.JTable tbSalesDetails;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID_delete;
    private javax.swing.JTextField txtID_edit;
    private javax.swing.JTextField txtProductname;
    private javax.swing.JTextField txtSupname;
    // End of variables declaration//GEN-END:variables
}
